Piv
ovh/the-bastion pull request #109
Opened 2020-12-30 10:45 UTC by speed47

2020-12-30 12:01 UTC, Alkorin commented on bin/plugin/open/selfAddIngressKey
> +    elsif ($pivImplicitGlobal) {
Twice the same "elsif"

2020-12-30 12:02 UTC, Alkorin commented on bin/plugin/open/selfAddIngressKey
> +    elsif ($pivImplicitGlobal) {
```suggestion
    elsif ($pivImplicitAccount) {
```

2020-12-30 12:11 UTC, Alkorin requested changes
See https://github.com/ovh/the-bastion/pull/109/files#r550170765

2020-12-30 17:58 UTC, Alkorin approved these changes

2020-12-31 16:17 UTC, speed47 commented
I'll also implement the notion of account-scoped "never" policy that override the global setting, it's not that much work and will be useful.

2020-12-31 16:17 UTC, closed without merging