Group generate egress key
ovh/the-bastion pull request #141
Opened 2021-02-15 13:39 UTC by speed47

2021-02-15 13:59 UTC, speed47 commented
This implements #135

2021-02-15 17:11 UTC, Alkorin requested changes

2021-02-15 17:11 UTC, Alkorin commented on bin/plugin/group-owner/groupDelEgressKey
> +    osh_exit 'ERR_INVALID_PARAMETER', "Couldn't find any key with the ID you specified ($id) in group $shortGroup";
```suggestion
    osh_exit 'ERR_INVALID_PARAMETER', "Couldn't find any key with the ID you specified ($id) in group $group";
```
?

2021-02-15 17:11 UTC, Alkorin commented on bin/helper/osh-groupDelEgressKey
> +    HEXIT('ERR_INVALID_PARAMETER', msg => "Couldn't find any key with the ID you specified ($id) in group $shortGroup");
```suggestion
    HEXIT('ERR_INVALID_PARAMETER', msg => "Couldn't find any key with the ID you specified ($id) in group $group");
```

2021-02-15 17:11 UTC, Alkorin commented on bin/plugin/group-owner/groupModify
> +    osh_exit 'ERR_NOT_GROUP_OWNER', "You must be an owner to delete an egress group key";
Wrong message ?

2021-02-15 17:11 UTC, Alkorin commented on lib/perl/OVH/Bastion/Plugin/generateEgressKey.pm
> +            return R('ERR_NOT_GROUP_OWNER', msg => "Sorry, you're not an owner of group $shortGroup, which is needed to manage its egress keys ($fnret)");
```suggestion
            return R('ERR_NOT_GROUP_OWNER', msg => "Sorry, you're not an owner of group $group, which is needed to manage its egress keys ($fnret)");
```

2021-02-15 17:11 UTC, Alkorin commented on lib/perl/OVH/Bastion/execute.inc
> -    #=cut only to debug tainted stuff
Mmm ?

2021-02-15 17:33 UTC, Alkorin approved these changes

2021-02-16 20:22 UTC, deathiop approved these changes

2021-02-17 09:03 UTC, merged