enh: make execute() way WAY faster
ovh/the-bastion pull request #338
Opened 2022-09-12 16:46 UTC by speed47

2022-09-13 09:09 UTC, deathiop commented
TODO: remove a layer of Perl references, refs to scalars are not needed

2022-09-13 09:10 UTC, deathiop requested changes
TODO: remove a layer of Perl references, refs to scalars are not needed

2022-09-13 16:41 UTC, speed47 commented
> TODO: remove a layer of Perl references, refs to scalars are not needed

fixed

2022-09-16 10:15 UTC, deathiop approved these changes

2022-09-21 09:57 UTC, merged