fix: osh.pl: validate user and host format
ovh/the-bastion pull request #56
Opened 2020-11-19 16:45 UTC by speed47

2020-11-19 16:50 UTC, deathiop requested changes
Couldn't it be tested?

2020-11-19 16:50 UTC, deathiop commented on bin/shell/osh.pl
> +if ($host !~ m{^[a-z0-9._-]+$}i) {
```suggestion
if ($host !~ m{^[a-zA-Z0-9._-]+$}) {
```

2020-11-19 17:37 UTC, speed47 commented on bin/shell/osh.pl
> +if ($host !~ m{^[a-z0-9._-]+$}i) {
Thx, applied

2020-11-19 17:42 UTC, speed47 commented
> Couldn't it be tested?

added tests

2020-11-19 17:48 UTC, Alkorin submitted a review, later dismissed

2020-11-19 18:41 UTC, speed47 commented
Gah, we get a 403 when fetching the latest ttyrec release from the API... probably rate limiting. Hmm.

2020-11-19 22:32 UTC, Alkorin submitted a review, later dismissed

2020-11-20 09:47 UTC, deathiop approved these changes

2020-11-20 09:59 UTC, merged